# Generated by Django 5.1.2 on 2024-11-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_profil', '0003_publication_author_alter_publication_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
